name: Publish Packages
on:
  workflow_call:
    inputs:
      KEY:
        required: true
        type: string
      REF:
        required: true
        type: string
      EVENT:
        required: true
        type: string
      BUILD_COMMAND:
        required: true
        type: string
      TEST_COMMAND:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      REPO_ACCESS_TOKEN:
        required: true

jobs:
  print-details:
    runs-on: ubuntu-latest
    name: Print execution details
    steps:
    - name: Print execution details
      run: |
        echo "Execution Context:"
        echo "KEY: ${{ inputs.KEY }}"
        echo "REF: ${{ inputs.REF }}"
        echo "EVENT: ${{ inputs.EVENT }}"
        echo "BUILD_COMMAND: ${{ inputs.BUILD_COMMAND }}"
        echo "TEST_COMMAND: ${{ inputs.TEST_COMMAND }}"
      
  initialize:
    name: Initialize CI environment
    uses: yaml-js/.github/.github/workflows/jobs.initialize-ci.yml@main
    secrets: inherit
    with:
      KEY: ${{ inputs.KEY }}

  build:
    needs: [initialize]
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Enable Corepack
      run: corepack enable
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - uses: actions/cache/restore@v4
      with:
        path: ./*
        key: ${{ inputs.KEY }}-workspace
    - name: Build packages
      run: ${{ inputs.BUILD_COMMAND }}
      shell: bash
    - uses: actions/cache/save@v4
      id: build-cache
      with:
        path: ./*
        key: ${{ inputs.KEY }}-build

  tests:
    needs: [build]
    name: Execute Tests & Code Analysis
    uses: yaml-js/.github/.github/workflows/jobs.tests.yml@main
    secrets: inherit
    with:
      KEY: ${{ inputs.KEY }}
      REF: ${{ inputs.REF }}
      EVENT: ${{ inputs.EVENT }}
      TEST_COMMAND: ${{ inputs.TEST_COMMAND }}
