name: Publish Packages
on:
  workflow_call:
    inputs:
      KEY:
        required: true
        type: string
      REF_NAME:
        required: true
        type: string
      INSTALL_DEPENDENCIES:
        required: false
        type: boolean
        default: true
      BUILD_COMMAND:
        required: true
        type: string
    secrets:
      NPMJS_ACCESS_TOKEN:
        required: true
      REPO_ACCESS_TOKEN:
        required: true

jobs:
  initialize:
    name: Initialize CI environment
    uses: yaml-js/.github/.github/workflows/jobs.initialize-ci.yml@main
    secrets: inherit
    with:
      KEY: ${{ inputs.KEY }}
      INSTALL_DEPENDENCIES: ${{ inputs.INSTALL_DEPENDENCIES }}

  publish:
    needs: [initialize]
    name: Publish Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Enable Corepack
      run: corepack enable
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - uses: actions/cache/restore@v4
      id: restore-cache-workspace
      with:
        path: ./*
        key: ${{ inputs.KEY }}-workspace
    - name: Bump Version of package.json
      uses: yaml-js/build/github-actions/update-package-version@v1
      with:
        tag: ${{ inputs.REF_NAME }}
        path: ./**/package.json
    - name: Build packages
      run: ${{ inputs.BUILD_COMMAND }}
      shell: bash
    - name: Publish Packages
      run: yarn deploy
      env:
        NPMJS_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
