name: Initialize CI environment
on:
  workflow_call:
    inputs:
      KEY:
        required: true
        type: string
      INSTALL_DEPENDENCIES:
        required: false
        type: boolean
        default: true

jobs:            
  initialize:
    name: Initialize CI environment
    runs-on: ubuntu-latest
    steps:
    - name: Enable Corepack
      run: corepack enable
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Clear Cache
      uses: uses: yaml-js/build/github-actions/clear-cache@v1
      with:
        prefix: ${{ inputs.KEY }}
    - name: Install dependencies
      if: steps.restore-cache-workspace.outputs.cache-hit != 'true' && inputs.INSTALL_DEPENDENCIES == true
      run: yarn install
    - uses: actions/cache/save@v4
      with:
        path: ./*
        key: ${{ inputs.KEY }}-workspace
